name: Test manual action run
on:
    workflow_dispatch:
      inputs:
        deploy-env:
          description: 'Which env you wanna deploy (production-api/production-web/production-cron-worker)'
          required: true
    push:
      branches:
        - production

jobs:
  activation:
    name: Print out the condition based on input
    runs-on: ubuntu-latest
    steps:
      - name: Print if input equal to production-web
        if: github.event.inputs.deploy-env == 'production-web'
        run: echo Do the deploy production web work here...
      - name: Print if input equal to production-api
        if: github.event.inputs.deploy-env == 'production-api'
        run: echo Do the deploy production api worke here...
      - name: Print if input equal to production-cron-worker
        if: github.event.inputs.deploy-env == 'production-cron-worker'
        run: echo Do the deploy productuon cron worker work here...
      - name: Test timeout
        run: sleep 2m
        timeout-minutes: 1
